config/routes.rb
Spree::Core::Engine.add_routes do

  get 'invoice/:id(/:template)', to: 'invoice#show'
  resources :users do
  	resources :user_addresses
  end

  resources :vendors do
    resources :contact_stores
  end

  get '/make_address_parimary', to: 'addresses#make_address_primary', as: 'make_address_primary'

end

app/models/spree/contact_store.rb
class Spree::ContactStore < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :user
  belongs_to :order

  after_create :send_email_to_vendor

  validates :query_type, :presence => {:message     => "Can't Blank" }
  validates :subject, :presence => {:message     => "Can't Blank" }
  validates :query, :presence => {:message     => "Can't Blank" }

  def send_email_to_vendor
    Spree::StoreContactMailer.send_email_to_vendor(self.vendor.name, "vendor@gmail.com").deliver_now
  end

end

app/controllers/spree/contact_stores_controller.rb
module Spree
  class ContactStoresController < Spree::StoreController
    before_action :load_required_objs, only: [:new,:create]

    def new
      @contact_store = @vendor.contact_stores.new
      @order  = spree_current_user.orders.find_by(number: params[:order_number])
    end

    def create

      @contact_store       = @vendor.contact_stores.new(contact_store_params)
      @contact_store.user  = @user
      @contact_store.order = @order
      lang = I18n.locale
      if @contact_store.save
        redirect_to spree.edit_account_path
      else
        render "spree/#{lang.present? ? lang.to_s : DEFAULT_VIEW_LANG}}/contact_stores/new"
      end
    end

    private

    def load_required_objs
      @vendor = Spree::Vendor.find(params[:vendor_id])
      @order  = spree_current_user.orders.find_by(number: params[:contact_store][:order_number]) if params[:contact_store].present?
      @user   = spree_current_user
    end

    def permitted_contact_store_attributes
      [:subject, :query, :query_type]
    end

    def contact_store_params
      params.require(:contact_store).permit(permitted_contact_store_attributes)
    end

  end
end

app/views/spree/ar/contact_stores/_form.html.erb
<div class="clearfix"></div>
<div class="container">

  <div class="alert">
    <% if @contact_store.errors.full_messages.any? %>
      <% @contact_store.errors.full_messages.each do |error_message| %>
      <%= error_message if @contact_store.errors.full_messages.first == error_message %> <br />
      <% end %>
    <% end %>
  </div>
  <div class="stor-full-top" dir="rtl">
    <div class="dv-title text-center col-md-12">
      <h2> ﺔﻴﺴﻧﺮﻔﻟ ﺔﻴﺴﻧﺮﻔﻟ</h2>
    </div>    
  </div>

  <div class="clearfix"></div>

  <div class="locan-stor cate-pg ord_pg cont-str-pg" dir="rtl"> 

    <div class="col-lg-10 col-md-10 col-sm-9 p-0 stor-return-pg" dir="rtl">

      <div class="col-lg-12 col-md-12 col-sm-12 p-0 det-ord-return"> 

        <div class="col-lg-12 col-md-12 col-sm-12 odr-return-main">
          <%= form_for @contact_store, url: vendor_contact_stores_path(@vendor.id), html: { method: :post } do |f| %>
            <div class="col-lg-12 col-md-12 col-sm-12 wet-text p-0">
              <p> ,ﺔﻴﺴﻧﺮﻔﻟﺍ ﻝّﻫﺃ ﻡﺎﻗﻭ ﻦﻋ ﻥﻻ ,ﺔﻳﺪﻴﻠﻘﺘﻟﺍ ﻦﻔﺴﻟﺍ ﻢﺗﻭ ﻞﻛ .ﻢﺛ ﻥﺪﻣ ﺭﻮﺤﻤﻟﺎﺑ ﺖﻣﺍ ﻝّﻫﺃ ﻡﺎﻗﻭ ﻦﻋ ﻥﻻ ,ﺔﻳﺪﻴﻠﻘﺘﻟﺍ ﻦﻔﺴﻟﺍ ﻢﺗﻭ ﻞﻛ .ﻢﺛ ﻥﺪﻣ  ,ﺔﻴﺴﻧﺮﻔﻟﺍ ﻝّﻫﺃ ﻡﺎﻗﻭ ﻦﻋ ﻥﻻ ,ﺔﻳﺪﻴﻠﻘﺘﻟﺍ ﻦﻔﺴﻟﺍ </p>
            </div>

            <div class="re_turn_person col-lg-12 col-md-12 col-sm-12 p-0 m-0">

              <ul class="col-lg-6 col-md-6 col-sm-6 p-0 order-back m-0 text-left">
                <li><button><a href="<%= spree.edit_account_path(partial: "orders")%>" style="color:black;" >ﺔﻳﺪﻴﻠﻘﺘﻟ</a></button></li>
                </ul>     

                <ul class="col-lg-6 col-md-6 col-sm-6 p-0 sedd_to">
                <li> ,<%=@vendor.name%> ﻡﺎﻗﻭ ﻦﻋ </li>
                <li><%=@order.number%>,ﺔﻳﺪﻴﻠﻘﺘﻟﺍ </li>
                <li>ﻦﻔﺴﻟﺍ ﻢﺗﻭ ﻞﻛ .ﻢﺛ ﻥﺪﻣ <%=@order.created_at.strftime("%e/%m/%Y")%> </li>
                <li>ﺭﻮﺤﻤﻟﺎﺑ ﺖﻣﺍ ﻝّﻫﺃ, <%=@order.line_items.count%> </li>
                <li>ﻥﻻ ,ﺔﻳﺪﻴﻠﻘﺘﻟﺍ ﻦﻔﺴﻟﺍ ﻢﺗﻭ 2</li>
              </ul>     

            </div>

            <div class="clearfix"></div>

            <div class="dvd"></div>

            <div class="clearfix"></div>

            <div class="general_qry">

              <div class="radio-dv">
                <p>
                 <%= f.radio_button :query_type, 'ﻥﻻ ,ﺔﻳﺪﻴﻠﻘﺘﻟﺍ', id: "test1", requied: true, checked:  true %>
                  <label for="test1">ﻥﻻ ,ﺔﻳﺪﻴﻠﻘﺘﻟﺍ </label>
                </p>

                <p>
                  <%= f.radio_button :query_type, 'ﺔﻴﺴﻧﺮﻔﻟﺍ', id: "test2" , requied: true%>
                  <label for="test2">ﺔﻴﺴﻧﺮﻔﻟﺍ</label>
                </p>

              </div>


            </div>

            <div class="return_details tp-qry-input">
              <label>ﻦﻔﺴﻟﺍ</label>
              <%= f.text_field :subject, maxlength: 255, size: 50, class: 'form-control', requied: true %>
              <%= f.hidden_field :order_number , value: @order.number.to_s %>
              <%= hidden_field_tag 'lang', 'ar' %>
            </div>

            <div class="ftr_not order-set-marg">
              <p> ,ﺔﻴﺴﻧﺮﻔﻟﺍ ﻝّﻫﺃ ﻡﺎﻗﻭ ﻦﻋ ﻥﻻ ,ﺔﻳﺪﻴﻠﻘﺘﻟﺍ ﻦﻔﺴﻟﺍ ﻢﺗﻭ ﻞﻛ .ﻢﺛ ﻥﺪﻣ ﺭﻮﺤﻤﻟﺎﺑ ﺖﻣﺍ ﻝّﻫﺃ ﻡﺎﻗﻭ ﻦﻋ ﻥﻻ ,ﺔﻳﺪﻴﻠﻘﺘﻟﺍ ﻦﻔﺴﻟﺍ ﻢﺗﻭ ﻞﻛ .ﻢﺛ ﻥﺪﻣ  ,ﺔﻴﺴﻧﺮﻔﻟﺍ ﻝّﻫﺃ ﻡﺎﻗﻭ ﻦﻋ ﻥﻻ ,ﺔﻳﺪﻴﻠﻘﺘﻟﺍ ﻦﻔﺴﻟﺍ ﻢﺗﻭ ﻞﻛ .ﻢﺛ ﻥﺪﻣ ﺭﻮﺤﻤﻟﺎﺑ ﺖﻣﺍ ﻝّﻫﺃ ﻡﺎﻗﻭ ﻦﻋ ﻥﻻ </p>
            </div>     

            <div class="return_details">
              <label>ﺔﻳﺪﻴﻠﻘﺘﻟﺍ ﻦﻔﺴﻟ</label>
              <%= f.text_area :query, maxlength: 255, size: 50, class: 'form-control', requied: true %>
              <div class="st-set-sub text-right">
                <%= f.submit "ﺔﻳﺪﻴﻠﻘﺘﻟ", class: 'sb_frm_return' %>
              </div>
            </div>

            <div class="clearfix"></div>
          <% end %>
        </div>
      </div>
    </div>
    <%= render  partial: "spree/ar/account_management/side_bar_tab" %>
  </div>
</div>

<div class="clearfix"></div>

<div class="adver-sec">
  <div class="container">
    <div class="adver-sec-mn"><%= image_tag "advertize.jpg", alt: "", class: "img-responsive"%> </div>
  </div>
</div>

app/views/spree/ar/contact_stores/new.html.erb
<%= render  'spree/ar/contact_stores/form'%>
<!-- <br />
<%#= link_to(spree.edit_account_path, target:  "_blank", class: "btn btn-primary") do %>
    Back to Account
<%# end %>
 -->