config/routes.rb
Spree::Core::Engine.add_routes do

  get 'invoice/:id(/:template)', to: 'invoice#show'
  resources :users do
  	resources :user_addresses
  end

  resources :vendors do
    resources :contact_stores
  end

  get '/make_address_parimary', to: 'addresses#make_address_primary', as: 'make_address_primary'

end

app/views/spree/en/account_management/address/_single_address.html.erb
<% @address_contents     = Spree::PageContent.from_gen_slug('address') %>
<% @address_btn_contents = @address_contents.from_gen_slug('address-btn-label') %>
<% @address_fileds_contents = @address_contents.from_gen_slug('address-field-label') %>

<% @user_shipping_address = (user.present? && user.shipping_address.present?) ?user.shipping_address.id  : "" %>
<% @user_billing_address = (user.present? && user.billing_address.present?) ? user.billing_address.id: "" %>

<% primary_address  = @address_contents.spec_slug('address-primary-heading').last%>
<% new_address      = @address_contents.spec_slug('address-new-address-heading').last%>
<% btn_primary      = @address_btn_contents.spec_slug('address-btn-label-primary').last%>
<% existing_address = @address_contents.spec_slug('address-existing-heading').last%>
<% @is_primary      = (@user_shipping_address || @user_billing_address ) == form_obj.id %>
<% update_address_btn   = @address_btn_contents.spec_slug('address-btn-label-save').last%>
<% save_address_btn     = @address_btn_contents.spec_slug('address-btn-label-new-save').last%>
<% delete_address_btn   = @address_btn_contents.spec_slug('address-btn-label-delete').last%>

<% Globalize.with_locale (I18n.locale) do %>


  <!-- <div class="<%#=  (from_view.present? && from_view == "address-checkout") ? "" : "col-md-4 well" %> <%#= @is_primary ? "primary-address " : "" %>">  -->

  <div class=" <%=  (from_view.present? && from_view == "address-checkout") ? "" : "col-lg-6 col-md-6 col-sm-6 prime-set prime-1" %>">
    <div class="street-box">

      <% if !@is_primary   %>
        <div class="prime-tp-btn">
         <ul>
         <li><%= @is_primary ? primary_address.try(:title) : (form_obj.persisted? ? existing_address.try(:title) : new_address.try(:title)) %></li>

          <% if form_obj.persisted? %>
           <li>
              <label class="switch"><input type="checkbox" , class="make-primary-checkbox", id="address_<%= form_obj.id %>"><span class="slider round"></span></label>
              <%= link_to "#", make_address_primary_path(id:form_obj.id), style: "display: none;", id: "make_me_primary_address_#{form_obj.id}", :remote => true %>
            </li>
          <% end %>
         </ul>
       </div>
      <% end %>


      <% if form_obj.persisted? && @is_primary %>
        <div class="prime-tp-btn">
         <button class="pp_x1">Primary Address</button>
        </div>
      <% end %>




      <%= form_for form_obj , html: { novalidate: true,  id: 'checkout_form_address', class: "needs-validation news_frm manage-frm-box" } ,remote: true do |form| %>

        <%= render partial: 'spree/en/addresses/form', locals: { address_form: form, address_type: 'billing', address: form_obj} %>
        <div class="clearfix"></div>

        <% if !(form_obj.persisted?) || @is_primary %>

          <div class="elit text-center yrt-input">
            <%= form.submit form.object.persisted? ? update_address_btn.try(:title) : save_address_btn.try(:title)  , :class => 'btn btn-primary btn-sm btn-sub-frm'%>
          </div>

        <% else %>

          <div class="elit-dd text-center manag-input">
            <%#= link_to delete_address_btn.try(:title) ,address_path(form.object), 'data-method' => :delete, :class => "ress-btn-delet",:data => {:confirm => 'Are you sure?'},:remote => true%>
              <button type="button" class="ress-btn-delete" data-toggle="modal" data-target="#Delete_confirm_modal_<%=form_obj.persisted? ? form_obj.id : 'new'%>">DELETE</button>
             <%#= form.submit form.object.persisted? ? update_address_btn.try(:title) : save_address_btn.try(:title)  , :class => 'ress-btn-save'%>
             <button class="ress-btn-save">SAVE</button>
          </div>

          <div id="Delete_confirm_modal_<%= form_obj.persisted? ? form_obj.id : 'new'%>" class="modal fade" role="dialog">
              <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content pr-pop-perso delet_pop_set">
                  <div class="modal-header">
                  <h2 class="popup-title">Delete Confirmation</h2>
                  </div>
                  <div class="modal-body">

                  <div class="review_da del-st">
                  <p>Please confirm you would like to delete this address from your addresses</p>

                  <div class="tr-v1-text">
                  <ul class="tower-lt">
                  <li class="la-1"><%= form_obj.firstname.to_s + " " + form_obj.lastname.to_s %></li>
                  <li class="la-2"><%= form_obj.phone %>
                  <%=  form_obj.address1%>,
                  <%=  form_obj.state.present? ? form_obj.state.name : ""%>,
                  <%=  form_obj.country.present? ? form_obj.country.name : ""%></li>
                  </ul>

                 <div class="clearfix"></div>
                    <div class="add-rev-btns pop-add-btns">
                   <button class="cancel-btn" data-dismiss="modal">Cancel</button>

                   <a  href="<%= address_path(form.object) %>" data-method="delete" data-remote="true"><button style="background: #ecb68f !important; color: #000 !important; border: 1px;" ><%= delete_address_btn.try(:title)  %></button></a>

                   </div>
                    </div>
                  </div>
                  </div>

                </div>

              </div>
            </div>


        <% end %>


      <% end%>
    </div>
  </div>

<% end %>

<!--


<script type="text/javascript">
  $("#make-me-primary").on('click', function(){

    alert('sadasd')
  });
</script> -->


 <!---Delete modal start ---->

app/views/spree/en/account_management/address/_user_addresses_section.html.erb
<% @address_contents     = Spree::PageContent.from_gen_slug('address') %>
<% @address_btn_contents = @address_contents.from_gen_slug('address-btn-label') %>
<% @address_fileds_contents = @address_contents.from_gen_slug('address-field-label') %>

<% @user_shipping_address = user.shipping_address.present? ?user.shipping_address.id  : "" %>
<% @user_billing_address = user.billing_address.present? ? user.billing_address.id: "" %>

<% primary_address     = addresses.select{|s| ( @user_shipping_address || @user_billing_address  ) == s.id}.last%>
<% secondry_addresses  = addresses.reject{|s| ( @user_shipping_address || @user_billing_address  ) == s.id} %>

<% if primary_address.present? %>
	<% secondry_addresses.insert(0,primary_address) %>
<% end %>

<% if addresses.any? %>
	<% secondry_addresses.in_groups_of(2).each  do |grouped_address_col| %>
		<div class="col-lg-12 col-md-12 col-sm-12 primary-dv-main p-0 mrt-20-top" >
			<% grouped_address_col.reject(&:blank?).each do |split_address| %>
				<%= render partial: 'spree/en/account_management/address/single_address', locals: {form_obj: split_address, url_name: address_path(split_address), method_name: "put",user: user,from_view: "pofile-addresses"}  %>
			<% end %>

			<% if grouped_address_col.compact.length == 1 %>
				<%= render partial: 'spree/en/account_management/address/single_address', locals: {form_obj: addresses.new, url_name: addresses_path(user), method_name: "post",user: user, from_view: "pofile-addresses"}  %>
			<% end %>
		</div>
	<% end %>
<% end %>


<% if  addresses.blank? || secondry_addresses.uniq.length%2==0 %>
	<div class="col-lg-12 col-md-12 col-sm-12 primary-dv-main p-0 mrt-20-top"  >
		<%= render partial: 'spree/en/account_management/address/single_address', locals: {form_obj: addresses.new, url_name: addresses_path(user), method_name: "post",user: user, from_view: "pofile-addresses"}  %>
	</div>
<% end  %>